### ISSUE TITLE
GitHub Commit Message Checker

### ISSUE THREAD

**Issue by morjo02jm** [hjoelh/Jira-Ticket-Bot#1]
Does your GitHub Commit Message Checker valid for a Jira ID within the commit message via a REGEX configuration and also integrates with Jira Data Center to ensure the Jira ID within the commit message is a valid Jira ID

**Comment by hjoelh** [comment]
@morjo02jm Sorry for the delay. The regex used to find the Jira ticket number/id from the PR title can be found here https://github.com/hjoelh/Jira-Ticket-Bot/blob/253f0dea0de48bcd69e157feb67e8bdf778083af/pages/api/github/webhooks.ts#L42 

The bot does **not** use the Jira Api to confirm if the ticket exists or not as this would require users giving over their Jira API key for little benefit.

Are you having any issues with the bot?

**Comment by morjo02jm** [comment]
The integration with Jira is most important to address human error with providing an incorrect Jira ID thus providing high value. This will ensure the Jira ID within the commit message is actual a validate Jira Issue. We have developed our own GitHub Commit Message Checker solution that performs this Jira ID validation. Thank You
